# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba777626c5cec1d81e97e933ed096f27417bd3002c762c33d7be3193299baea8a3d3012b57f53178d46d3a31b3ff56e025c86cada3be5bf63b9d9e915077033b

test:
  secret_key_base: df569042f1f80a92f5e8d695ebfd5a265f6ac7d23d4593b7323a62c769be696407b55734b5994efa68ec98dbea84bb63739672af0c91c36105c02fe530a185c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
